apiVersion: v1
kind: Service
metadata:
  name: banking-service
  labels:
    app.kubernetes.io/name: banking-service-service
    app.kubernetes.io/component: Service
    app.kubernetes.io/part-of: banking
spec:
  type: ClusterIP
  selector:
    app: banking-service
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-service
  labels:
    app.kubernetes.io/name: banking-service-deployment
    app.kubernetes.io/component: Frontend
    app.kubernetes.io/part-of: banking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-service
  template:
    metadata:
      labels:
        app: banking-service
        app.kubernetes.io/name: banking-service-replicaset
        app.kubernetes.io/component: ReplicaSet
        app.kubernetes.io/part-of: banking-service
    spec:
      containers:
        - name: banking-service
          image: danielr1996/banking-service
          imagePullPolicy: Always
#          env:
#            - name: GRAPHQL_API
#              value: http://api.banking.danielr1996.de
          ports:
            - containerPort: 9090
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: banking-service
  labels:
    app.kubernetes.io/name: banking-service-ingress
    app.kubernetes.io/component: Ingress
    app.kubernetes.io/part-of: banking
spec:
  rules:
    - host: api.banking.danielr1996.de
      http:
        paths:
          - backend:
              serviceName: banking-service
              servicePort: 80
---
