spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgresdb
#    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    database: postgresql
  liquibase:
    contexts: data-prod
