spring:
  profiles:
    active: db, db-h2, fints-mock, hbcicallback-wamp, keys-file, logging-plain
logging:
  config: classpath:logging/logback.xml
server:
  port: 9090
management:
  endpoints:
    web:
      exposure:
        include: prometheus,metrics,info,health
#management:
#  endpoint:
#    metrics:
#      enabled: true
#      export:
#        prometheus:
#          enabled: true
#    web:
#      exposure:
#        include: "*"
