spring:
  output:
    ansi:
      enabled: always
  profiles:
    active: db, db-h2
server:
  port: 9090
#okta:
#  oauth2:
#    issuer: https://dev-648405.okta.com/oauth2/default
#    clientId: 0oa1c188ahG9TJbDt357
#    scopes: 'email profile openid'
