name: 'docker-action'
description: 'Build and publish docker images'
author: 'Daniel Richter'
branding:
  icon: 'box'
  color: 'blue'
inputs:
  imagename:
    description: 'Name of the created image'
    required: true
  imagetag:
    description: 'Tag of the created image'
    default: latest
  dockeruser:
    description: 'Dockerhub user'
    required: true
  dockerpassword:
    description: 'Dockerhub pasword'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
