apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -local
commonLabels:
  app.kubernetes.io/instance: local
  app.kubernetes.io/version: 0.0.1
bases:
  - ../../base

patchesStrategicMerge:
  - deployment.yaml
patchesJson6902:
  - target:
      group: extensions
      version: v1beta1
      kind: Ingress
      name: banking-service
    path: ingress.yaml
