apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -master
commonLabels:
  app.kubernetes.io/instance: master
  app.kubernetes.io/version: 2.0.0
bases:
  - ../../base
patchesJson6902:
  - target:
      group: extensions
      version: v1beta1
      kind: Ingress
      name: banking-service
    path: ingress.yaml
