apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres-service
    spec:
      containers:
        - name: postgres
          image: postgres:12.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pvc
