apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app.kubernetes.io/name: postgres-service
    app.kubernetes.io/component: Service
    app.kubernetes.io/part-of: banking
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postgres-service
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
---
