apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -${INSTANCE}
commonLabels:
  app.kubernetes.io/instance: ${INSTANCE}
  app.kubernetes.io/version: 0
bases:
  - ../../base

patchesStrategicMerge:
  - deployment.yaml
patchesJson6902:
  - target:
      group: extensions
      version: v1beta1
      kind: Ingress
      name: banking-service
    path: ingress.yaml
