name: CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: rlespinasse/github-slug-action@master
      - uses: danielr1996/docker-action-multitag@1.0.0
        with:
          imagename: danielr1996/banking-service
          imagetags: |
            ${{ env.GITHUB_REF_SLUG }}
            ${{ env.GITHUB_SHA_SHORT }}
          dockeruser: ${{ secrets.DOCKER_USERNAME }}
          dockerpassword: ${{ secrets.DOCKER_PASSWORD }}
      - uses: danielr1996/kubectl-action@0.1.0
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
        env:
          VERSION: ${{ env.GITHUB_SHA_SHORT }}
          INSTANCE: ${{ env.GITHUB_REF_SLUG }}
