name: CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: rlespinasse/github-slug-action@master
      - name: Print slug variables
        run: |
          echo ${{ env.GITHUB_REF_SLUG }}
          echo ${{ env.GITHUB_HEAD_REF_SLUG }}
          echo ${{ env.GITHUB_BASE_REF_SLUG }}
          echo ${{ env.GITHUB_SHA_SHORT }}
      - name: Sanitize branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | tr / -)"
        id: sanitize
      - name: Sanitize branch name
        shell: bash
        run: echo "##[set-output name=sha;]$(git rev-parse --short $GITHUB_SHA)"
        id: sha
      - name: Build
        uses: ./.github/actions/docker-action
        with:
          # TODO: Use Github User and Repository Name
          imagename: danielr1996/banking-service
          imagetag: ${{ steps.sanitize.outputs.branch }}
          dockeruser: ${{ secrets.DOCKER_USERNAME }}
          dockerpassword: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy
        uses: ./.github/actions/kubectl-deploy-action
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          args: apply -f deployment.yaml
        env:
          VERSION: ${{ steps.sha.outputs.sha }}
          INSTANCE: ${{ steps.sanitize.outputs.branch }}
